### ISSUE TITLE
Improve CMake build

### ISSUE THREAD

**Issue by SnPb** [duckduckgo/bloom_cpp#7]
Some suggestions for changes/cleanup to the CMake build structure that would help to position better for extensions with other tooling - such as #6 - for example:

- Using a recursive arrangement and an `add_directory()` can make a build harder to follow for small projects, so consolidation could be considered simpler for a project with only a few source files
- The Catch2 library is built and linked, but it just needs to be included as a single header
- Explicitly setting the `CMAKE_CXX_COMPILER` as g++ makes the build less easy to use with clang, for example - these settings are usually best factored out to related toolchain files and referenced on the command line as `-CMAKE_TOOLCHAIN_FILE=`
- The file `empty.cpp` looks like a holdover from an earlier stage, and isn't needed now for CMake to figure out the linker language
- The bloom filter library in the `CMakeLists.txt` references the hpp file, which shouldn't be needed as it's not an independent translation unit

And related:
- Using Catch2 as single header usually means splitting out a separate test runner cpp file to reduce recompile times, also better for scaling up test suite sizes

**Comment by hellozee** [comment]
If no one is on it, I could give it a try.
One question, the third_party directory is not included in the CMakeLists.txt of the root but the Catch2 is loaded as a submodule? Is this intentional?

**Comment by subsymbolic** [comment]
Thanks for the great suggestions @klutz. I think you were considering implementing some of these? In case you are (or for anyone else that might come along and work on this), I have added my htoughts below

> Using a recursive arrangement...

I'm open to this, as long as our bash scripts etc continue to run.

> The Catch2 just needs to be included as a single header

Sounds good 👍 

> Explicitly setting the `CMAKE_CXX_COMPILER` as g++...

We'll defer this as it is convenient internally for us to specify it. If, in the future, someone needs this change we'll reconsider.

> The file `empty.cpp`... isn't needed now for CMake to figure out the linker language

It was added after a compilation issue. I'm happy to remove it provided that the project still compiles across platforms.

> The bloom filter library in the `CMakeLists.txt` references the hpp file, which shouldn't be needed as it's not an independent translation unit.

> Using Catch2 as single header usually means splitting out a separate test runner cpp file to reduce recompile times, also better for scaling up test suite sizes.

They sound like good tidy ups 👍

**Comment by subsymbolic** [comment]
Thanks for the input all. I'm now closing this, we'll iterate on the build structure and work in the above suggestions on an as-needed basis during development.
